qe-collaborative-services/1115-hub

src/ahc-hrsn-elt/screening/csv.ts
src/ahc-hrsn-elt/screening/sqlpage.ts
support/infrastructure/containers/Dockerfile.workflow

- Added code for merging individual CSV tables into unified table set
- Updated sqlpage code to query the data from the unified table set .
- Fixed the relative file path issue of cwd for crontab.

Merge individual CSV table sets into unified table set #22

---

src/ahc-hrsn-elt/screening/csv.ts

Replaced hardcoded table names in csv using index with const.

Replace hardcoded table names in csv using index with const #22

---

src/ahc-hrsn-elt/screening/csv.ts
src/ahc-hrsn-elt/screening/orchestrate.ts

feat: remove unique value validation for FACILITY_ID #29

---

src/ahc-hrsn-elt/screening/orchestrate.ts
support/infrastructure/containers/Dockerfile.workflow
support/infrastructure/containers/docker-compose.yaml

- Updated the QE ID as per the expectations of the FHIR API endpoints.
- Updated the passwords of the respective QEs.
- version updated 0.8.0.

Use proper QE ID expected by FHIR endpoints

---

src/ahc-hrsn-elt/screening/csv.ts
src/ahc-hrsn-elt/screening/governance.ts
src/ahc-hrsn-elt/screening/orchestrate.ts

Update version to 0.9.1

---

src/ahc-hrsn-elt/screening/csv.ts
src/ahc-hrsn-elt/screening/orchestrate.ts

Update version to 0.10.4

---

src/ahc-hrsn-elt/screening/csv.ts
src/ahc-hrsn-elt/screening/governance.ts
src/ahc-hrsn-elt/screening/orchctl.ts
src/ahc-hrsn-elt/screening/orchestrate.ts
src/ahc-hrsn-elt/screening/test-e2e.ts
support/docs/diagnostics.md
support/docs/sandbox.md

- Add structural group validation for csv tables
- Modified structural group validation query for csv tables
- Fixed FHIR view if aggregated tables exist
- Made FHIR JSON per encounter per person
- Added documentation for setting up a test sandbox
- Added documentation for diagnostics information
- Version update to 0.12.0

upgrade to version 0.12.0

---

src/ahc-hrsn-elt/screening/orchestrate.ts
support/infrastructure/bin/infrastructure.ts

- Modified the 1115 compute instance instance type from "t3.micro" to "t3.medium".
- Made the ids for observation unique & logical.

upgrade version to 0.12.2

---

src/ahc-hrsn-elt/screening/orchctl.ts
src/ahc-hrsn-elt/screening/orchestrate.ts
src/ahc-hrsn-elt/screening/test-e2e.ts

- Add RECORDED_TIME as an encrypted value to the Observation ID.
- Introduced ingress transactions to reduce orphan file opportunities.

Upgrade to version 0.13.0

---

support/docs/fhir-expanded.drawio.svg
support/docs/self-sufficient-architecture.drawio.svg

Update the architecture diagram to make it current. Add the expanded workflow for FHIR processing

doc: updates to architecture diagram

---

src/ahc-hrsn-elt/reference-data/business-rules.csv
src/ahc-hrsn-elt/screening/orch-http-service.ts
src/ahc-hrsn-elt/screening/orch-services.http
src/ahc-hrsn-elt/screening/orchestrate.ts
src/ahc-hrsn-elt/screening/sessions-merge.ts

- Updated some of the QCS validation rules to match omnibus FHIR definitions.
- Work in progress for orchestration HTTP service.
- Work in progress for implementation aggregated content storage to Amazon Aurora PostgreSQL.

Upgrade to version 0.16.0

---

src/ahc-hrsn-elt/screening/orch-http-service.ts

- Updated code for incoming zip files, orchestrate them and emit the complete session as zip.

Introduce orchestration HTTP service - work in progress

---

src/ahc-hrsn-elt/screening/orch-http-service.ts
src/ahc-hrsn-elt/screening/orch-services.http

- Updated code for all files, orchestrate them and emit the complete session as zip and emit. 
- Updated the .http yac file.

Introduce orchestration HTTP service - work in progress #126

---

src/service/fhir-server-prime/README.md
src/service/fhir-server-prime/pom.xml
src/service/fhir-server-prime/src/main/java/org/techbd/FHIRBundleValidator.java
src/service/fhir-server-prime/src/main/java/org/techbd/Hints.java
src/service/fhir-server-prime/src/main/java/org/techbd/Msg.java
src/service/fhir-server-prime/src/main/java/org/techbd/PlainRestfulServer.java
src/service/fhir-server-prime/src/main/resources/application.properties
src/service/fhir-server-prime/src/main/resources/logback.xml
src/service/fhir-server-prime/src/main/webapp/WEB-INF/web.xml
src/service/fhir-server-prime/src/main/webapp/WEB-INF/xsd/javaee_6.xsd
src/service/fhir-server-prime/src/main/webapp/WEB-INF/xsd/jsp_2_2.xsd
src/service/fhir-server-prime/src/main/webapp/WEB-INF/xsd/web-app_3_0.xsd
src/service/fhir-server-prime/src/main/webapp/WEB-INF/xsd/web-common_3_0.xsd
src/service/fhir-server-prime/src/main/webapp/WEB-INF/xsd/xml.xsd

Introduces a new FHIR service to the project, enhancing its capabilities to handle FHIR resources. The service includes two new endpoints for Bundle validation and Bundle submission, providing essential functionality for the system.
This service adds FHIR service endpoints for Bundle validation and submission.
These endpoints enable the system to validate and submit FHIR Bundles, improving interoperability and data exchange within the application.

feat: add FHIR service endpoints #123

---

src/ahc-hrsn-elt/screening/deps.ts
src/ahc-hrsn-elt/screening/governance.ts
src/ahc-hrsn-elt/screening/orchestrate.ts
support/infrastructure/containers/Dockerfile.workflow

- Upgraded the duckdb version to 0.10.2.

Upgrade to version 0.17.0

---

src/ahc-hrsn-elt/screening/governance.ts
src/ahc-hrsn-elt/screening/orchestrate.ts

- Fix done for validation of score calculation which prevents the generation of FHIR json.

Upgrade to version 0.17.1

---

src/service/fhir-server-prime/README.md
src/service/fhir-server-prime/pom.xml
src/service/fhir-server-prime/src/main/java/org/techbd/DatabaseConnector.java
src/service/fhir-server-prime/src/main/java/org/techbd/FHIRBundleValidator.java
src/service/fhir-server-prime/src/main/resources/application.properties

update README with sandbox installation
update code for postgress option

feat:  update README with sandbox installation

---

support/assurance/ahc-hrsn-elt/screening/results-test-e2e/fhir-service/2024-05-03/README.md
support/assurance/ahc-hrsn-elt/screening/results-test-e2e/fhir-service/2024-05-03/fhir-fixture-shinny-impl-guide-sample.json
support/assurance/ahc-hrsn-elt/screening/results-test-e2e/fhir-service/2024-05-03/fhir-fixture-unhappy-path-01.json
support/assurance/ahc-hrsn-elt/screening/results-test-e2e/fhir-service/2024-05-03/fhir-service-result.txt
support/assurance/ahc-hrsn-elt/screening/results-test-e2e/fhir-service/2024-05-03/fhir-service.test.http

- update daily  fhir service .http test results

Daily fhir service .http test results

---

support/assurance/ahc-hrsn-elt/screening/results-test-e2e/fhir-service/2024-05-03/README.md

Updated daily fhir service .http test results readme file.

Daily fhir service .http test results readme update

---

support/assurance/ahc-hrsn-elt/screening/results-test-e2e/fhir-service/2024-05-15/README.md
support/assurance/ahc-hrsn-elt/screening/results-test-e2e/fhir-service/2024-05-15/fhir-service-result.txt
support/assurance/ahc-hrsn-elt/screening/results-test-e2e/fhir-service/2024-05-15/fhir-service.test.http

- Updated the httpyac results with the version 0.23.0

Daily fhir service .http test results with the version 0.23.0

---

src/service/fhir-server-prime/pom.xml
src/service/fhir-server-prime/src/main/java/org/techbd/hrsn/assurance/FHIRBundleValidator.java
src/service/fhir-server-prime/src/main/java/org/techbd/hrsn/assurance/OrchestrationSession.java
src/service/fhir-server-prime/src/main/java/org/techbd/service/http/FhirController.java
src/service/fhir-server-prime/src/main/resources/application.properties
src/service/fhir-server-prime/src/main/resources/home.md

Changes:
1. HTML response for /admin/diagnostics
2. HTML response for /admin/diagnostics/{sessionId}
3. Home page /with markdown content as HTML

feat: add md content as HTML for home page and HTML response for admin diagnostic APIs #123

---

src/service/fhir-server-prime/src/main/java/org/techbd/hrsn/assurance/FHIRBundleValidator.java
src/service/fhir-server-prime/src/main/java/org/techbd/hrsn/assurance/Globals.java
src/service/fhir-server-prime/src/main/java/org/techbd/hrsn/assurance/OrchestrationSession.java
src/service/fhir-server-prime/src/main/java/org/techbd/service/http/FhirService.java
src/service/fhir-server-prime/src/main/java/org/techbd/service/http/filter/RequestResponseBundleFilter.java
src/service/fhir-server-prime/src/main/resources/application.properties

Changes
- orchestration start time and end time to microseconds precision
- Device Id correction

feat: orchestration start time and end time to microseconds precision #123

---

src/ahc-hrsn-elt/screening/orchestrate.ts

- Fix for lastUpdated format in FHIR bundle JSON.
- Fix for FullURL & Identifier.system as absolute URL in FHIR bundle JSON.
- Update for Language code in FHIR bundle JSON.
- Updated the gender mapping for CSV to FHIR.

Upgrade to version 0.23.6

---

src/ahc-hrsn-elt/screening/orchestrate.ts

Update version to 0.31.0

---

src/ahc-hrsn-elt/screening/orchestrate.ts

- Added phone and SSN fields to the FHIR JSON structure.

Update to version 0.31.1

---

src/ahc-hrsn-elt/screening/csv.ts
src/ahc-hrsn-elt/screening/orchestrate.ts

- Fixed the issue with casting to the fields where they tend to belong to multiple data types.

Update to version 0.31.2

---

src/ahc-hrsn-elt/screening/csv.ts
src/ahc-hrsn-elt/screening/orchestrate.ts

- Fixed  - #189
- Duckdb version upgraded to 1.0.0

Update to version 0.32.0

---

src/ahc-hrsn-elt/screening/orchestrate.ts
support/containers/synthetic.sftp.qualifiedentity.org/workflow/Dockerfile
support/containers/synthetic.sftp.techbd.org/workflow/Dockerfile

- updated duckdb version to 1.0.0

Update version to 0.40.0

---

src/ahc-hrsn-elt/screening/orchestrate.ts

- Updated race/Ethnicity to be OMB category only for those OMBcategories and rest should be detailed.

upgrade version to 0.42.0

---

src/ahc-hrsn-elt/screening/orchestrate.ts

- Fixed logical IDs to 64 char by hashing them.

Upgrade to version 0.43.0
